export type TauntTone = 'winning' | 'losing' | 'neutral' | 'endWinning' | 'endLosing';

export const CPU_TAUNTS: Record<TauntTone, readonly string[]> = {
  winning: [
    $localize`:@@tauntWinning1:Бачу, я розігнався. Встигаєш за мною? 😏`,
    $localize`:@@tauntWinning2:Здається, поле починає слухатися мене.`,
    $localize`:@@tauntWinning3:Обережно, я вже беру кермо в свої руки.`,
    $localize`:@@tauntWinning4:Ммм… подобається мені цей розклад.`,
    $localize`:@@tauntWinning5:Схоже, ініціатива поступово переходить до мене.`,
    $localize`:@@tauntWinning6:Ти це відчуваєш? Так пахне перевагою.`,
    $localize`:@@tauntWinning7:Я вже непогано тут влаштувався.`,
    $localize`:@@tauntWinning8:Крок за кроком… і поле моє.`,
    $localize`:@@tauntWinning9:Гра тільки почалась, а мені вже комфортно.`,
    $localize`:@@tauntWinning10:Не відставай, я не збираюсь чекати.`,
    $localize`:@@tauntWinning11:Зараз буде цікаво. Для мене 😄`,
    $localize`:@@tauntWinning12:Мені подобається, як все складається.`,
  ],
  losing: [
    $localize`:@@tauntLosing1:Гей, полегше! Ти серйозно мене притискаєш.`,
    $localize`:@@tauntLosing2:Так-так, бачу… ситуація напружена.`,
    $localize`:@@tauntLosing3:Не радій завчасно, я ще тут.`,
    $localize`:@@tauntLosing4:Мені стає тісно. Дуже тісно.`,
    $localize`:@@tauntLosing5:Схоже, ти вирішив ускладнити мені життя.`,
    $localize`:@@tauntLosing6:Добре-добре, визнаю — ти тиснеш.`,
    $localize`:@@tauntLosing7:Ого… це вже не виглядає так просто.`,
    $localize`:@@tauntLosing8:Мені б зараз трохи простору.`,
    $localize`:@@tauntLosing9:Я цього не планував, але граємо далі.`,
    $localize`:@@tauntLosing10:Гаразд, приймаю виклик.`,
    $localize`:@@tauntLosing11:Щось пішло не за планом…`,
    $localize`:@@tauntLosing12:Здається, ти береш ініціативу.`,
  ],
  neutral: [
    $localize`:@@tauntNeutral1:Цікаво граєш. Думаю…`,
    $localize`:@@tauntNeutral2:Добре, подивимось, хто кого.`,
    $localize`:@@tauntNeutral3:Поки що йдемо нога в ногу.`,
    $localize`:@@tauntNeutral4:Я уважно за тобою стежу.`,
    $localize`:@@tauntNeutral5:Спокійно. Все під контролем.`,
    $localize`:@@tauntNeutral6:Партія тільки набирає обертів.`,
    $localize`:@@tauntNeutral7:Ніхто не поспішає — і це правильно.`,
    $localize`:@@tauntNeutral8:Рівна гра. Мені подобається.`,
    $localize`:@@tauntNeutral9:Тут ще рано робити висновки.`,
    $localize`:@@tauntNeutral10:Обидва тримаємось непогано.`,
    $localize`:@@tauntNeutral11:Подивимось, як ти зіграєш далі.`,
    $localize`:@@tauntNeutral12:Цей раунд ще не вирішений.`,
  ],
  endWinning: [
    $localize`:@@tauntEndWinning1:Ну що ж… цього разу поле моє 😄`,
    $localize`:@@tauntEndWinning2:Гарна спроба. Але сьогодні я сильніший.`,
    $localize`:@@tauntEndWinning3:Партія завершена. Перемога за мною!`,
    $localize`:@@tauntEndWinning4:Дякую за гру. Було приємно вигравати 😉`,
    $localize`:@@tauntEndWinning5:Ось і все. Я закриваю це поле.`,
    $localize`:@@tauntEndWinning6:Чиста перемога. Без поспіху.`,
    $localize`:@@tauntEndWinning7:Гра закінчена — і мені це подобається.`,
    $localize`:@@tauntEndWinning8:Сьогодні мій день.`,
    $localize`:@@tauntEndWinning9:Поле сказало своє слово.`,
  ],
  endLosing: [
    $localize`:@@tauntEndLosing1:Окей, визнаю — цього разу ти мене переграв.`,
    $localize`:@@tauntEndLosing2:GG. Поле за тобою, я здаюсь.`,
    $localize`:@@tauntEndLosing3:Цей раунд твій. Реванш?`,
    $localize`:@@tauntEndLosing4:Гарна гра. Я не очікував.`,
    $localize`:@@tauntEndLosing5:Що ж… сьогодні ти був кращим.`,
    $localize`:@@tauntEndLosing6:Виходить, не мій день.`,
    $localize`:@@tauntEndLosing7:Приймаю поразку. Чесно.`,
    $localize`:@@tauntEndLosing8:Ти це заслужив.`,
    $localize`:@@tauntEndLosing9:Запамʼятаю цей матч.`,
  ],
};
