services:
  filler-frontend:
    image: ghcr.io/vitaliytyupa/filler-frontend:latest
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.filler.rule=Host(`filler.leo-lab.app`)"
      - "traefik.http.routers.filler.entrypoints=web"
      - "traefik.http.services.filler.loadbalancer.server.port=80"

  filler-backend:
    image: ghcr.io/vitaliytyupa/filler-backend:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: ${MONGODB_URI}
    networks:
      - web
      - mongo_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.filler-api.rule=Host(`api.leo-lab.app`)"
      - "traefik.http.routers.filler-api.entrypoints=web"
      - "traefik.http.services.filler-api.loadbalancer.server.port=3000"

networks:
  web:
    external: true
  mongo_net:
    external: true
